### ISSUE TITLE
debug exception should be removed at the appropriate time

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#44]
```
java.lang.Exception: kivakit-testing on ProjectInformationMojo @ 548408077
[663](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:664)
	at com.telenav.cactus.maven.ParallelismDiagnosticsLogger$Diagnostic.<init>(ParallelismDiagnosticsLogger.java:209)
[664](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:665)
	at com.telenav.cactus.maven.ParallelismDiagnosticsLogger.logDiagnostic(ParallelismDiagnosticsLogger.java:102)
[665](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:666)
	at com.telenav.cactus.maven.ProjectInformationMojo.diagnostics(ProjectInformationMojo.java:87)
[666](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:667)
	at com.telenav.cactus.maven.ProjectInformationMojo.performTasks(ProjectInformationMojo.java:66)
[667](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:668)
	at com.telenav.cactus.maven.mojobase.BaseMojo.lambda$run$3(BaseMojo.java:654)
[668](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:669)
	at com.telenav.cactus.maven.log.BuildLog.lambda$run$0(BuildLog.java:140)
[669](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:670)
	at com.telenav.cactus.maven.log.BuildLog.withLog(BuildLog.java:88)
[670](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:671)
	at com.telenav.cactus.maven.log.BuildLog.run(BuildLog.java:136)
[671](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:672)
	at com.telenav.cactus.maven.mojobase.BaseMojo.run(BaseMojo.java:651)
[672](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:673)
	at com.telenav.cactus.maven.mojobase.BaseMojo.execute(BaseMojo.java:355)
[673](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:674)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[674](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:675)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
[675](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:676)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
[676](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:677)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
[677](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:678)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
[678](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:679)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
[679](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:680)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[680](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:681)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[681](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:682)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
[682](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:683)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[683](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:684)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[684](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:685)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[685](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:686)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[686](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:687)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[687](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:688)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[688](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:689)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[689](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:690)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[690](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:691)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[691](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:692)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[692](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:693)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[693](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:694)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[694](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:695)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[695](https://github.com/Telenav/kivakit-extensions/runs/7979334691?check_suite_focus=true#step:41:696)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by timboudreau** [comment]
I haven't the faintest idea what the description of this ticket means.

**Comment by jonathanl-telenav** [comment]
then what is this exception if not a debug trace?

**Comment by timboudreau** [comment]
No idea how every line of the stack trace got a URL embedded in it, but this is debug code for tracking down why we appeared to be building some projects twice in ProjectInformationMojo.

I'll turn that off.

Speaking of which, did you ever test if topologically-presorting all the `<module>` entries made any difference for your ability to run parallel builds?

**Comment by timboudreau** [comment]
Stacks are now disabled [unless a system property is set](https://github.com/Telenav/cactus/commit/6be4fd3f137def3ba42ac1d673e5754ee68517bb)
