### ISSUE TITLE
strange thread dump

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#54]
any idea where this came from?

```
[INFO] Running com.telenav.cactus.test.project.generator.BranchCleanupTest
[main] INFO BuildLog - [develop 8fdd110] Initial content for root repo
[main] INFO BuildLog -  1 file changed, 23 insertions(+)
[main] INFO BuildLog -  create mode 100644 pom.xml
Maven location is /Users/jonathan/Developer/apache-maven-3.8.5/bin/mvn

 -------- Thread Dump for PID 50120 --------
2022-08-31 11:33:48
Full thread dump OpenJDK 64-Bit Server VM (17.0.3+6-LTS mixed mode, sharing):

Threads class SMR info:
_java_thread_list=0x00006000006d2c80, length=13, elements={
0x00007f9b8b00a800, 0x00007f9b6b008200, 0x00007f9b6b80a400, 0x00007f9b8a808c00,
0x00007f9b8a809200, 0x00007f9b8a813000, 0x00007f9b8a813600, 0x00007f9b8a81f400,
0x00007f9b8a81fa00, 0x00007f9b8c812800, 0x00007f9b6b80c000, 0x00007f9b6b043400,
0x00007f9b8b00ae00
}

"main" #1 prio=5 os_prio=31 cpu=98.59ms elapsed=0.17s tid=0x00007f9b8b00a800 nid=0x1703 runnable  [0x0000700003ec2000]
   java.lang.Thread.State: RUNNABLE
	at jdk.internal.ref.CleanerImpl.getCleanerImpl(java.base@17.0.3/CleanerImpl.java:77)
	at jdk.internal.ref.PhantomCleanable.<init>(java.base@17.0.3/PhantomCleanable.java:67)
	at jdk.internal.ref.CleanerImpl$PhantomCleanableRef.<init>(java.base@17.0.3/CleanerImpl.java:164)
	at java.lang.ref.Cleaner.register(java.base@17.0.3/Cleaner.java:220)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.<init>(java.base@17.0.3/ZipFile.java:426)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.<init>(java.base@17.0.3/ZipFile.java:419)
	at java.util.zip.ZipFile.getInputStream(java.base@17.0.3/ZipFile.java:386)
	- locked <0x00000010800d4798> (a java.util.jar.JarFile)
	at java.util.jar.JarFile.getInputStream(java.base@17.0.3/JarFile.java:842)
	- locked <0x00000010800d4798> (a java.util.jar.JarFile)
	at jdk.internal.loader.URLClassPath$JarLoader$2.getInputStream(java.base@17.0.3/URLClassPath.java:879)
	at jdk.internal.loader.Resource.cachedInputStream(java.base@17.0.3/Resource.java:77)
	- locked <0x0000001080a3a028> (a jdk.internal.loader.URLClassPath$JarLoader$2)
	at jdk.internal.loader.Resource.getByteBuffer(java.base@17.0.3/Resource.java:163)
	at java.net.URLClassLoader.defineClass(java.base@17.0.3/URLClassLoader.java:511)
	at java.net.URLClassLoader$1.run(java.base@17.0.3/URLClassLoader.java:427)
	at java.net.URLClassLoader$1.run(java.base@17.0.3/URLClassLoader.java:421)
	at java.security.AccessController.executePrivileged(java.base@17.0.3/AccessController.java:807)
	at java.security.AccessController.doPrivileged(java.base@17.0.3/AccessController.java:712)
	at java.net.URLClassLoader.findClass(java.base@17.0.3/URLClassLoader.java:420)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClassFromSelf(ClassRealm.java:425)
	- locked <0x0000001080a38d90> (a java.lang.Object)
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:42)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	at org.apache.maven.extension.internal.CoreExtensionEntry.<clinit>(CoreExtensionEntry.java:82)
	at org.apache.maven.cli.MavenCli.container(MavenCli.java:631)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@17.0.3/Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@17.0.3/NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@17.0.3/DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(java.base@17.0.3/Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

"Reference Handler" #2 daemon prio=10 os_prio=31 cpu=0.10ms elapsed=0.15s tid=0x00007f9b6b008200 nid=0x3e03 waiting on condition  [0x00007000045dd000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.ref.Reference.waitForReferencePendingList(java.base@17.0.3/Native Method)
	at java.lang.ref.Reference.processPendingReferences(java.base@17.0.3/Reference.java:253)
	at java.lang.ref.Reference$ReferenceHandler.run(java.base@17.0.3/Reference.java:215)

"Finalizer" #3 daemon prio=8 os_prio=31 cpu=0.16ms elapsed=0.15s tid=0x00007f9b6b80a400 nid=0x3f03 in Object.wait()  [0x00007000046e0000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.3/Native Method)
	- waiting on <0x0000001080002f30> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.3/ReferenceQueue.java:155)
	- locked <0x0000001080002f30> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.3/ReferenceQueue.java:176)
	at java.lang.ref.Finalizer$FinalizerThread.run(java.base@17.0.3/Finalizer.java:172)

"Signal Dispatcher" #4 daemon prio=9 os_prio=31 cpu=0.16ms elapsed=0.15s tid=0x00007f9b8a808c00 nid=0xa503 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Service Thread" #5 daemon prio=9 os_prio=31 cpu=0.02ms elapsed=0.15s tid=0x00007f9b8a809200 nid=0x5a03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Deflation Thread" #6 daemon prio=9 os_prio=31 cpu=0.02ms elapsed=0.15s tid=0x00007f9b8a813000 nid=0x5b03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=31 cpu=27.35ms elapsed=0.15s tid=0x00007f9b8a813600 nid=0x5c03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   Compiling:  359   !   4       java.util.zip.ZipFile$Source::checkAndAddEntry (209 bytes)

"C1 CompilerThread0" #15 daemon prio=9 os_prio=31 cpu=30.47ms elapsed=0.15s tid=0x00007f9b8a81f400 nid=0x5d03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   Compiling:  392       3       java.net.URLStreamHandler::parseURL (1201 bytes)

"Sweeper thread" #19 daemon prio=9 os_prio=31 cpu=0.02ms elapsed=0.15s tid=0x00007f9b8a81fa00 nid=0x5f03 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread1" #16 daemon prio=9 os_prio=31 cpu=27.01ms elapsed=0.15s tid=0x00007f9b8c812800 nid=0x6103 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
   No compile task

"Common-Cleaner" #20 daemon prio=8 os_prio=31 cpu=0.07ms elapsed=0.14s tid=0x00007f9b6b80c000 nid=0x6203 in Object.wait()  [0x0000700004ffe000]
   java.lang.Thread.State: TIMED_WAITING (on object monitor)
	at java.lang.Object.wait(java.base@17.0.3/Native Method)
	- waiting on <0x000000108004a428> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(java.base@17.0.3/ReferenceQueue.java:155)
	- locked <0x000000108004a428> (a java.lang.ref.ReferenceQueue$Lock)
	at jdk.internal.ref.CleanerImpl.run(java.base@17.0.3/CleanerImpl.java:140)
	at java.lang.Thread.run(java.base@17.0.3/Thread.java:833)
	at jdk.internal.misc.InnocuousThread.run(java.base@17.0.3/InnocuousThread.java:162)

"Notification Thread" #21 daemon prio=9 os_prio=31 cpu=0.04ms elapsed=0.14s tid=0x00007f9b6b043400 nid=0x6303 runnable  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #22 daemon prio=9 os_prio=31 cpu=0.45ms elapsed=0.10s tid=0x00007f9b8b00ae00 nid=0x6403 waiting on condition  [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"VM Thread" os_prio=31 cpu=0.30ms elapsed=0.16s tid=0x00007f9b7a707190 nid=0x4603 runnable

"GC Thread#0" os_prio=31 cpu=0.06ms elapsed=0.16s tid=0x00007f9b8b808570 nid=0x4c03 runnable

"G1 Main Marker" os_prio=31 cpu=0.02ms elapsed=0.16s tid=0x00007f9b8b808c10 nid=0x4b03 runnable

"G1 Conc#0" os_prio=31 cpu=0.02ms elapsed=0.16s tid=0x00007f9b8b809490 nid=0x3203 runnable

"G1 Refine#0" os_prio=31 cpu=0.04ms elapsed=0.16s tid=0x00007f9b8b80d0f0 nid=0x4903 runnable

"G1 Service" os_prio=31 cpu=0.03ms elapsed=0.16s tid=0x00007f9b8b80d980 nid=0x4703 runnable

"VM Periodic Task Thread" os_prio=31 cpu=0.09ms elapsed=0.14s tid=0x00007f9b6a8063f0 nid=0x9e03 waiting on condition

JNI global refs: 17, weak refs: 0

**Comment by timboudreau** [comment]
It's for debugging stalled Maven tasks it github actions, since I was having a problem with processes going into a black hole and never exiting or doing anything, there and only there, in order to see where they were stuck.  So, when a maven process is launched, a reference is kept to it, and a background thread periodically runs `jstack $PID` so we can see where it is stuck if it is.  Since it's a simple 2 minute sleep-loop timer, a process may get dumped fairly soon after it was launched later in the build.

I've switched it to be controlled by an environment variable, which will only be turned on in github actions for cactus, so you shouldn't see it locally anymore.
