### ISSUE TITLE
kill queue failure

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#69]
```
Exception in thread "Process timeout killer" java.util.ConcurrentModificationException
	at java.base/java.util.WeakHashMap$HashIterator.nextEntry(WeakHashMap.java:809)
	at java.base/java.util.WeakHashMap$EntryIterator.next(WeakHashMap.java:848)
	at java.base/java.util.WeakHashMap$EntryIterator.next(WeakHashMap.java:846)
	at java.base/java.util.AbstractCollection.addAll(AbstractCollection.java:335)
	at java.base/java.util.HashSet.<init>(HashSet.java:121)
	at com.telenav.cactus.process.KillQueue.leastInterval(KillQueue.java:87)
	at com.telenav.cactus.process.KillQueue.killLoop(KillQueue.java:108)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by timboudreau** [comment]
Hrm, what this needs is a `ConcurrentWeakHashMap<ProcessControl<?, ?>, Long>`, and there is no such beast unless we want to depend on Guava or Caffeine.

I'll come up with a different data structure that still avoids a strong reference to the `ProcessControl` (and thus everything associated with the process, which, if it has disappeared, has already exited and can't possibly need killing - that is the common case).  `DelayQueue<SomeSortOfPairOf<WeakReference<ProcessControl<?,?>>, Long>>` would do it.

**Comment by timboudreau** [comment]
That said, this is probably lower priority - while it means the kill-on-timeout thread is dead, in the common case, that's not going to interfere with a build completing.

**Comment by timboudreau** [comment]
Fixed, with tests.
