### ISSUE TITLE
corrupted channel bug is back

### ISSUE THREAD

**Issue by jonathanl-telenav** [Telenav/cactus-build#78]
```
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[WARNING] Corrupted channel by directly writing to native stream in forked JVM 1. See FAQ web page and the dump file /Users/jonathan/Workspaces/telenav-build/kivakit/kivakit-collections/target/surefire-reports/2022-10-11T17-07-55_300-jvmRun1.dumpstream
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] telenav-root-superpom 1.0.2 ........................ SUCCESS [  0.158 s]
[INFO] telenav-superpom-project-family 2.0.3 .............. SUCCESS [  0.007 s]
[INFO] telenav-superpom-intermediate-bom 2.0.2 ............ SUCCESS [  0.004 s]
[INFO] telenav-superpom 2.0.4 ............................. SUCCESS [  0.006 s]
[INFO] cactus 1.5.32 ...................................... SUCCESS [  0.111 s]
[INFO] cactus-maven-log 1.5.32 ............................ SUCCESS [  0.938 s]
[INFO] cactus-util 1.5.32 ................................. SUCCESS [  0.962 s]
[INFO] cactus-process 1.5.32 .............................. SUCCESS [  1.497 s]
[INFO] cactus-cli 1.5.32 .................................. SUCCESS [  5.858 s]
[INFO] cactus-git 1.5.32 .................................. SUCCESS [  1.011 s]
[INFO] cactus-maven-xml 1.5.32 ............................ SUCCESS [  0.476 s]
[INFO] cactus-maven-model 1.5.32 .......................... SUCCESS [  1.191 s]
[INFO] cactus-graph 1.5.32 ................................ SUCCESS [  0.184 s]
[INFO] cactus-metadata 1.5.32 ............................. SUCCESS [  0.533 s]
[INFO] cactus-scope 1.5.32 ................................ SUCCESS [  0.087 s]
[INFO] cactus-maven-versioning 1.5.32 ..................... SUCCESS [  0.231 s]
[INFO] cactus-tasks 1.5.32 ................................ SUCCESS [  0.672 s]
[INFO] cactus-codeflowers 1.5.32 .......................... SUCCESS [  0.130 s]
[INFO] cactus-maven-plugin 1.5.32 ......................... SUCCESS [  3.555 s]
[INFO] telenav-superpom-project 2.0.4 ..................... SUCCESS [  0.056 s]
[INFO] telenav-superpom-mesakit 2.0.11 .................... SUCCESS [  0.006 s]
[INFO] telenav-superpom-lexakai 2.0.11 .................... SUCCESS [  0.004 s]
[INFO] telenav-superpom-kivakit 2.1.1 ..................... SUCCESS [  0.005 s]
[INFO] telenav-superpom-bom 2.0.2 ......................... SUCCESS [  0.019 s]
[INFO] kivakit-annotations 1.7.1-SNAPSHOT ................. SUCCESS [  0.196 s]
[INFO] lexakai-annotations 1.0.7-SNAPSHOT ................. SUCCESS [  0.090 s]
[INFO] kivakit-interfaces 1.7.1-SNAPSHOT .................. SUCCESS [  0.251 s]
[INFO] kivakit-mixins 1.7.1-SNAPSHOT ...................... SUCCESS [  0.085 s]
[INFO] kivakit-core 1.7.1-SNAPSHOT ........................ SUCCESS [  1.716 s]
[INFO] kivakit-internal-testing 1.7.1-SNAPSHOT ............ SUCCESS [  0.149 s]
[INFO] kivakit-collections 1.7.1-SNAPSHOT ................. FAILURE [  0.869 s]
[INFO] kivakit-conversion 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-validation 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-commandline 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit-resource 1.7.1-SNAPSHOT .................... SKIPPED
[INFO] kivakit-testing 1.7.1-SNAPSHOT ..................... SKIPPED
[INFO] kivakit-internal-tests-resource 1.7.1-SNAPSHOT ..... SKIPPED
[INFO] kivakit-extraction 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-internal-tests-core 1.7.1-SNAPSHOT ......... SKIPPED
[INFO] kivakit-internal-tests 1.7.1-SNAPSHOT .............. SKIPPED
[INFO] kivakit-internal 1.7.1-SNAPSHOT .................... SKIPPED
[INFO] kivakit-serialization-core 1.7.1-SNAPSHOT .......... SKIPPED
[INFO] kivakit-serialization-properties 1.7.1-SNAPSHOT .... SKIPPED
[INFO] kivakit-serialization-kryo 1.7.1-SNAPSHOT .......... SKIPPED
[INFO] kivakit-serialization-kryo-testing 1.7.1-SNAPSHOT .. SKIPPED
[INFO] kivakit-serialization-gson 1.7.1-SNAPSHOT .......... SKIPPED
[INFO] kivakit-serialization 1.7.1-SNAPSHOT ............... SKIPPED
[INFO] kivakit-settings 1.7.1-SNAPSHOT .................... SKIPPED
[INFO] kivakit-network-core 1.7.1-SNAPSHOT ................ SKIPPED
[INFO] kivakit-network-ftp 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit-network-http 1.7.1-SNAPSHOT ................ SKIPPED
[INFO] kivakit-network-socket 1.7.1-SNAPSHOT .............. SKIPPED
[INFO] kivakit-network-email 1.7.1-SNAPSHOT ............... SKIPPED
[INFO] kivakit-network 1.7.1-SNAPSHOT ..................... SKIPPED
[INFO] kivakit-component 1.7.1-SNAPSHOT ................... SKIPPED
[INFO] kivakit-application 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit 1.7.1-SNAPSHOT ............................. SKIPPED
[INFO] wordy 1.5.32 ....................................... SKIPPED
[INFO] cactus-tests 1.5.32 ................................ SKIPPED
[INFO] kivakit-web-jetty 1.7.1-SNAPSHOT ................... SKIPPED
[INFO] kivakit-web-jersey 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-web-swagger 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit-web-wicket 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-web 1.7.1-SNAPSHOT ......................... SKIPPED
[INFO] kivakit-metrics-core 1.7.1-SNAPSHOT ................ SKIPPED
[INFO] kivakit-metrics-prometheus 1.7.1-SNAPSHOT .......... SKIPPED
[INFO] kivakit-metrics 1.7.1-SNAPSHOT ..................... SKIPPED
[INFO] kivakit-settings-stores-zookeeper 1.7.1-SNAPSHOT ... SKIPPED
[INFO] kivakit-settings-stores 1.7.1-SNAPSHOT ............. SKIPPED
[INFO] kivakit-microservice 1.7.1-SNAPSHOT ................ SKIPPED
[INFO] kivakit-logs-file 1.7.1-SNAPSHOT ................... SKIPPED
[INFO] kivakit-logs-email 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-logs 1.7.1-SNAPSHOT ........................ SKIPPED
[INFO] kivakit-extensions 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-examples-settings 1.7.1-SNAPSHOT ........... SKIPPED
[INFO] kivakit-examples-lambda 1.7.1-SNAPSHOT ............. SKIPPED
[INFO] kivakit-examples-application 1.7.1-SNAPSHOT ........ SKIPPED
[INFO] kivakit-examples-microservice 1.7.1-SNAPSHOT ....... SKIPPED
[INFO] kivakit-examples 1.7.1-SNAPSHOT .................... SKIPPED
[INFO] kivakit-math 1.7.1-SNAPSHOT ........................ SKIPPED
[INFO] kivakit-service-registry 1.7.1-SNAPSHOT ............ SKIPPED
[INFO] kivakit-service-client 1.7.1-SNAPSHOT .............. SKIPPED
[INFO] kivakit-service-server 1.7.1-SNAPSHOT .............. SKIPPED
[INFO] kivakit-service-viewer 1.7.1-SNAPSHOT .............. SKIPPED
[INFO] kivakit-service 1.7.1-SNAPSHOT ..................... SKIPPED
[INFO] kivakit-security 1.7.1-SNAPSHOT .................... SKIPPED
[INFO] kivakit-ui-desktop 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-ui 1.7.1-SNAPSHOT .......................... SKIPPED
[INFO] kivakit-primitive-collections 1.7.1-SNAPSHOT ....... SKIPPED
[INFO] kivakit-logs-server 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit-logs-client 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit-logs-viewer 1.7.1-SNAPSHOT ................. SKIPPED
[INFO] kivakit-remote-log 1.7.1-SNAPSHOT .................. SKIPPED
[INFO] kivakit-data-formats-library 1.7.1-SNAPSHOT ........ SKIPPED
[INFO] kivakit-data-formats-csv 1.7.1-SNAPSHOT ............ SKIPPED
[INFO] kivakit-data-formats-xml 1.7.1-SNAPSHOT ............ SKIPPED
[INFO] kivakit-data-formats 1.7.1-SNAPSHOT ................ SKIPPED
[INFO] kivakit-data-compression 1.7.1-SNAPSHOT ............ SKIPPED
[INFO] kivakit-data 1.7.1-SNAPSHOT ........................ SKIPPED
[INFO] kivakit-stuff 1.7.1-SNAPSHOT ....................... SKIPPED
[INFO] lexakai 1.0.13-SNAPSHOT ............................ SKIPPED
[INFO] mesakit-core 0.9.18-SNAPSHOT ....................... SKIPPED
[INFO] mesakit-map-measurements 0.9.18-SNAPSHOT ........... SKIPPED
[INFO] mesakit-map-shapefile 0.9.18-SNAPSHOT .............. SKIPPED
[INFO] mesakit-map-geography 0.9.18-SNAPSHOT .............. SKIPPED
[INFO] mesakit-map-measurements-testing 0.9.18-SNAPSHOT ... SKIPPED
[INFO] mesakit-map-geography-testing 0.9.18-SNAPSHOT ...... SKIPPED
[INFO] mesakit-map-ui-desktop 0.9.18-SNAPSHOT ............. SKIPPED
[INFO] mesakit-map-ui-debug 0.9.18-SNAPSHOT ............... SKIPPED
[INFO] mesakit-map-utilities-grid 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-map-data-library 0.9.18-SNAPSHOT ........... SKIPPED
[INFO] mesakit-map-data-formats-pbf 0.9.18-SNAPSHOT ....... SKIPPED
[INFO] mesakit-map-region 0.9.18-SNAPSHOT ................. SKIPPED
[INFO] mesakit-map-overpass 0.9.18-SNAPSHOT ............... SKIPPED
[INFO] mesakit-map-road-model 0.9.18-SNAPSHOT ............. SKIPPED
[INFO] mesakit-map-region-testing 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-map-road-name-parser 0.9.18-SNAPSHOT ....... SKIPPED
[INFO] mesakit-map-road-name-standardizer 0.9.18-SNAPSHOT . SKIPPED
[INFO] mesakit-graph-core 0.9.18-SNAPSHOT ................. SKIPPED
[INFO] mesakit-map-utilities-geojson 0.9.18-SNAPSHOT ...... SKIPPED
[INFO] mesakit-map-cutter 0.9.18-SNAPSHOT ................. SKIPPED
[INFO] mesakit-graph-world 0.9.18-SNAPSHOT ................ SKIPPED
[INFO] mesakit-graph-core-testing 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-graph-world-testing 0.9.18-SNAPSHOT ........ SKIPPED
[INFO] mesakit-navigation-routing 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-navigation 0.9.18-SNAPSHOT ................. SKIPPED
[INFO] mesakit-map-utilities-geohash 0.9.18-SNAPSHOT ...... SKIPPED
[INFO] mesakit-map-utilities 0.9.18-SNAPSHOT .............. SKIPPED
[INFO] mesakit-map-data-formats 0.9.18-SNAPSHOT ........... SKIPPED
[INFO] mesakit-map-data 0.9.18-SNAPSHOT ................... SKIPPED
[INFO] mesakit-map-ui 0.9.18-SNAPSHOT ..................... SKIPPED
[INFO] mesakit-map-road 0.9.18-SNAPSHOT ................... SKIPPED
[INFO] mesakit-map 0.9.18-SNAPSHOT ........................ SKIPPED
[INFO] mesakit-graph-query 0.9.18-SNAPSHOT ................ SKIPPED
[INFO] mesakit-graph 0.9.18-SNAPSHOT ...................... SKIPPED
[INFO] mesakit-internal-map-region-unit-tests 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-internal-graph-core-unit-tests 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-internal-map-measurements-unit-tests 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-internal-map-geography-unit-tests 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-internal 0.9.18-SNAPSHOT ................... SKIPPED
[INFO] mesakit 0.9.18-SNAPSHOT ............................ SKIPPED
[INFO] mesakit-tools-applications-pbf-metadata 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-region-information 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-to-graph-converter 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-comparator 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-graph-double-digitized-ways-extractor 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-analyzer 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-dumper 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-region-extractor 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-graph-analyzer 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-graph-verifier 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-world-graph-extractor 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-pbf-filter 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-graph-dumper 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-codec-generator 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-graph-to-pbf-converter 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications-graph-slicer 0.9.18-SNAPSHOT SKIPPED
[INFO] mesakit-tools-applications 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-tools-application-launcher 0.9.18-SNAPSHOT . SKIPPED
[INFO] mesakit-tools 0.9.18-SNAPSHOT ...................... SKIPPED
[INFO] mesakit-plugins-josm-library 0.9.18-SNAPSHOT ....... SKIPPED
[INFO] mesakit-plugins-josm-graph 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-plugins-josm-geojson 0.9.18-SNAPSHOT ....... SKIPPED
[INFO] mesakit-plugins-josm 0.9.18-SNAPSHOT ............... SKIPPED
[INFO] mesakit-plugins 0.9.18-SNAPSHOT .................... SKIPPED
[INFO] mesakit-geocoding 0.9.18-SNAPSHOT .................. SKIPPED
[INFO] mesakit-serialization-json 0.9.18-SNAPSHOT ......... SKIPPED
[INFO] mesakit-serialization 0.9.18-SNAPSHOT .............. SKIPPED
[INFO] mesakit-extensions 0.9.18-SNAPSHOT ................. SKIPPED
[INFO] mesakit-map-examples 0.9.18-SNAPSHOT ............... SKIPPED
[INFO] mesakit-examples 0.9.18-SNAPSHOT ................... SKIPPED
[INFO] telenav-build 2.0.2 ................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.123 s
[INFO] Finished at: 2022-10-11T17:08:15-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project kivakit-collections:
[ERROR]
[ERROR] Please refer to /Users/jonathan/Workspaces/telenav-build/kivakit/kivakit-collections/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] Error occurred in starting fork, check output in log
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: Error occurred in starting fork, check output in log
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:635)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:311)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:268)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1334)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1167)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:931)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:301)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:211)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:165)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:157)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:121)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:127)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:294)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:960)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR]
[ERROR] -> [Help 1]

**Comment by timboudreau** [comment]
If you see this again, follow these instructions *in the output from Maven* and attach what's in this directory:

> Please refer to /Users/jonathan/Workspaces/telenav-build/kivakit/kivakit-collections/target/surefire-reports for the individual test results.

This problem can be caused by *anything* that calls `System.setOut()` or `System.setErr()` or writes to `System.out` or `System.err` *between test runs* (e.g. something that runs in a background thread or VM shutdown hook, and tries to log to stdout or stderr).  That could be test code, test harness code or the code that was tested.

The files in that directory will contain the raw process output.  If we have that and what tests failed to execute, we might have a chance of examining the output and figuring out *what* was writing output.  Without that, no clue.

Updating to `maven-surefire-plugin` version `3.0.0-M7` cured most occurrences of this problem.  Is there any chance one project was still using an older version?  kivakit-collections doesn't seem to be now, but no idea if it did have its own stanza for that when this run happened.
